import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
// import "bootstrap-icons/font/bootstrap-icons.css";
import { Jost } from "next/font/google";

const jost = Jost({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${jost.className} antialiased`}
      >
        <div className="fixed top-0 left-0 z-[-2] min-h-full w-full bg-black bg-[radial-gradient(#ffffff33_1px,#000000_1px)] bg-[size:20px_20px]"></div>
        <Link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200&display=swap"
          rel="stylesheet"
        ></Link>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
